version: '3.9'

services:
  web:
    container_name: web
    image: singuuu/singuuu.github.io:latest
    ports:
      - 80:80
    networks:
      - npm
      
networks:
  npm:
    name: npm
    external: true