services:
  web:
    image: registry.singu.dev/web/web:$${env.IMAGE_VERSION}
    ports:
      - 80:80
    networks:
      - web

networks:
  web:
    external: false
    name: web
    driver: overlay
